version: '3.5'

services:
  rails_app:
    container_name: "rails_app"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links: 
      - redis_db
  redis_db:
    container_name: "redis_db"
    image: redis
    ports:
      - "6379:6379"
